name: Go Linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2.0.3
    - name: Build project
      working-directory: .
      run: go build
  lint:
    runs-on: ubuntu-latest
    container: golangci/golangci-lint
    steps:
      - uses: actions/checkout@v2
      - name: Lint project
        run: golangci-lint run --out-format=github-actions
